name: BrowserStack Web Tests

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop

jobs:
  setup-wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Set up WireGuard tunnel
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools
          echo "[Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = 10.0.0.2/24
          DNS = 8.8.8.8

          [Peer]
          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
          AllowedIPs = 0.0.0.0/0
          Endpoint = ${{ secrets.WG_SERVER_ADDRESS }}
          PersistentKeepalive = 25" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo wg-quick up wg0

      - name: Verify WireGuard status
        run: |
          sudo wg show

  inji-web-test:
    needs: setup-wireguard
    uses: mosip/kattu/.github/workflows/browserstack-web.yml@master-java21
    with:
      SERVICE_LOCATION: inji-web-test
      BUILD_ARTIFACT: test-output
    secrets:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
